# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_d4beta <- function(x, shape1, shape2, a, b) {
    .Call('_RcppDist_test_d4beta', PACKAGE = 'RcppDist', x, shape1, shape2, a, b)
}

test_p4beta <- function(x, shape1, shape2, a, b) {
    .Call('_RcppDist_test_p4beta', PACKAGE = 'RcppDist', x, shape1, shape2, a, b)
}

test_q4beta_nolog <- function(x, shape1, shape2, a, b) {
    .Call('_RcppDist_test_q4beta_nolog', PACKAGE = 'RcppDist', x, shape1, shape2, a, b)
}

test_q4beta_log <- function(x, shape1, shape2, a, b) {
    .Call('_RcppDist_test_q4beta_log', PACKAGE = 'RcppDist', x, shape1, shape2, a, b)
}

test_dlst <- function(x, df, mu, sigma) {
    .Call('_RcppDist_test_dlst', PACKAGE = 'RcppDist', x, df, mu, sigma)
}

test_plst <- function(x, df, mu, sigma) {
    .Call('_RcppDist_test_plst', PACKAGE = 'RcppDist', x, df, mu, sigma)
}

test_qlst_nolog <- function(x, df, mu, sigma) {
    .Call('_RcppDist_test_qlst_nolog', PACKAGE = 'RcppDist', x, df, mu, sigma)
}

test_qlst_log <- function(x, df, mu, sigma) {
    .Call('_RcppDist_test_qlst_log', PACKAGE = 'RcppDist', x, df, mu, sigma)
}

test_dtruncnorm <- function(x, mu, sigma, a, b) {
    .Call('_RcppDist_test_dtruncnorm', PACKAGE = 'RcppDist', x, mu, sigma, a, b)
}

test_ptruncnorm <- function(x, mu, sigma, a, b) {
    .Call('_RcppDist_test_ptruncnorm', PACKAGE = 'RcppDist', x, mu, sigma, a, b)
}

test_qtruncnorm_nolog <- function(x, mu, sigma, a, b) {
    .Call('_RcppDist_test_qtruncnorm_nolog', PACKAGE = 'RcppDist', x, mu, sigma, a, b)
}

test_qtruncnorm_log <- function(x, mu, sigma, a, b) {
    .Call('_RcppDist_test_qtruncnorm_log', PACKAGE = 'RcppDist', x, mu, sigma, a, b)
}

test_dtrunct <- function(x, df, a, b) {
    .Call('_RcppDist_test_dtrunct', PACKAGE = 'RcppDist', x, df, a, b)
}

test_ptrunct <- function(x, df, a, b) {
    .Call('_RcppDist_test_ptrunct', PACKAGE = 'RcppDist', x, df, a, b)
}

test_qtrunct_nolog <- function(x, df, a, b) {
    .Call('_RcppDist_test_qtrunct_nolog', PACKAGE = 'RcppDist', x, df, a, b)
}

test_qtrunct_log <- function(x, df, a, b) {
    .Call('_RcppDist_test_qtrunct_log', PACKAGE = 'RcppDist', x, df, a, b)
}

test_dtrunclst <- function(x, df, mu, sigma, a, b) {
    .Call('_RcppDist_test_dtrunclst', PACKAGE = 'RcppDist', x, df, mu, sigma, a, b)
}

test_ptrunclst <- function(x, df, mu, sigma, a, b) {
    .Call('_RcppDist_test_ptrunclst', PACKAGE = 'RcppDist', x, df, mu, sigma, a, b)
}

test_qtrunclst_nolog <- function(x, df, mu, sigma, a, b) {
    .Call('_RcppDist_test_qtrunclst_nolog', PACKAGE = 'RcppDist', x, df, mu, sigma, a, b)
}

test_qtrunclst_log <- function(x, df, mu, sigma, a, b) {
    .Call('_RcppDist_test_qtrunclst_log', PACKAGE = 'RcppDist', x, df, mu, sigma, a, b)
}

test_dtri <- function(x, a, b, c) {
    .Call('_RcppDist_test_dtri', PACKAGE = 'RcppDist', x, a, b, c)
}

test_ptri <- function(x, a, b, c) {
    .Call('_RcppDist_test_ptri', PACKAGE = 'RcppDist', x, a, b, c)
}

test_qtri_nolog <- function(x, a, b, c) {
    .Call('_RcppDist_test_qtri_nolog', PACKAGE = 'RcppDist', x, a, b, c)
}

test_qtri_log <- function(x, a, b, c) {
    .Call('_RcppDist_test_qtri_log', PACKAGE = 'RcppDist', x, a, b, c)
}

test_dmvnorm <- function(x, mu, S) {
    .Call('_RcppDist_test_dmvnorm', PACKAGE = 'RcppDist', x, mu, S)
}

test_dmvt <- function(x, mu, S, df) {
    .Call('_RcppDist_test_dmvt', PACKAGE = 'RcppDist', x, mu, S, df)
}

test_dwish <- function(x, df, S) {
    .Call('_RcppDist_test_dwish', PACKAGE = 'RcppDist', x, df, S)
}

test_diwish <- function(x, df, S) {
    .Call('_RcppDist_test_diwish', PACKAGE = 'RcppDist', x, df, S)
}

